# Do initial research on the important document types and come up with 
# a list of questions that are relevant to the document type that are highly likely
# to be asked by the end user.

# The important thing about the questions is that each question should be answerable from one document of the type.

# The current set of questions is generated by brainstorming with Gemini 2.5 Pro with iterative refinement.

release_question_templates = [
    # 📊 Core Financials (investors, analysts)
    "What was the total revenue?",
    "What was the year-over-year (YoY) revenue growth?",
    "What was the operating income and operating margin?",
    "What was the net income?",
    "What was the diluted earnings per share (EPS)?",
    "How did free cash flow change?",
    "What was the effective tax rate?",

    # 🏢 Segment Results (management, competitors, analysts)
    "What were the revenues of each segment?",
    "What was each segment’s operating income (or loss)?",
    "How did segment revenue change compared to the previous quarter?",
    "What percentage of total revenue did each segment contribute?",
    "How did advertising revenues perform?",
    "What was YouTube Ads revenue?",
    "What was Search & Other revenue?",
    "What was Network revenue?",
    "What was each segment’s year-over-year growth?",

    # 👩‍💼 Workforce & Operations (employees, management, journalists)
    "How many employees were reported?",
    "What changes to workforce size or structure were announced?",
    "What were the total operating expenses?",
    "What were the research and development (R&D) expenses?",
    "What were the sales and marketing expenses?",
    "What were the general and administrative (G&A) expenses?",
    "What were the capital expenditures?",
    "What infrastructure or data center investments were highlighted?",

    # 💰 Capital Return & Balance Sheet (investors, analysts)
    "What dividend was declared, and when was it payable?",
    "Was a stock repurchase program announced or expanded?",
    "What was the cash, cash equivalents, and marketable securities balance?",
    "What was the total debt?",
    "What was the debt-to-equity ratio?",

    # 📈 Outlook & Guidance (investors, management)
    "What financial guidance was provided?",
    "What revenue or operating margin guidance was provided for future periods?",
    "What capital expenditure outlook was provided?",
    "What risks or uncertainties were highlighted?",
    "What regulatory or legal matters were mentioned?",
    "What competitive threats or industry trends were discussed?",

    # 🚀 Strategy, Innovation & Products (employees, competitors, customers)
    "What product launches or updates were announced?",
    "What AI or other technology initiatives were highlighted?",
    "What regions or markets were expanded into?",
    "What customer adoption or usage statistics were shared?",
    "What partnerships or collaborations were announced?",
    "What acquisitions or divestitures were mentioned?",

    # ⚖️ Governance & ESG (regulators, journalists, employees)
    "Were any regulatory actions or legal proceedings discussed?",
    "Were any environmental, social, or governance (ESG) initiatives reported?",
    "Were there any changes in leadership or board composition?",
    "Were sustainability or climate-related commitments mentioned?",
    "Were risks related to data privacy or security disclosed?",

    # 📰 Narrative & Miscellaneous (all audiences)
    "What key themes were emphasized?",
    "How did management describe overall performance?",
    "What major challenges were highlighted?",
    "What future priorities were outlined?",
    "Were macroeconomic conditions such as inflation or foreign exchange mentioned?"
]

slides_question_templates = [
    # 📈 Trends & Growth
    "What multi-quarter trends are displayed for revenue, income, or EPS?",
    "What multi-quarter trends are displayed for capital expenditures or free cash flow?",
    "What year-over-year (YoY) growth charts are shown for revenue or earnings?",
    "What YoY growth charts are shown across different business segments?",
    "What regional or market performance charts are presented?",

    # 🏢 Segment & Margin Visuals
    "What segment revenue trends are displayed?",
    "What segment operating margin trends are displayed?",
    "What percentage of total revenue is attributed to each segment in charts?",

    # 💰 Expense & Cost Breakdown
    "What charts are shown for R&D, sales and marketing, or G&A expenses?",
    "What traffic acquisition costs (TAC) trends are displayed?",
    "What total operating expense trends are displayed?",

    # 🏗️ Investments & Cash Flow
    "What charts are presented for capital expenditures (CapEx)?",
    "What charts are presented for free cash flow (FCF)?",
    "What charts are presented for cash and marketable securities?",

    # ⚖️ Non-GAAP & Reconciliations
    "What non-GAAP financial measures are presented in the slides?",
    "What reconciliations between GAAP and non-GAAP figures are included?",
    "What adjusted margin or earnings measures are displayed?",

    # 📰 Other Slide-Specific Elements
    "What forward-looking cautionary statements are included in the slides?",
    "What key themes or messages are highlighted visually in the presentation?"
]
